image: docker:stable

services:
  - name: docker:28.1.1-dind
    alias: docker

stages:
  - build
  - push

variables:
  IMAGE_NAME: registry.gitlab.com/vivividolov-group/trackMate
  DEFAULT_TAG: latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

after_script:
  - docker logout registry.gitlab.com

build-image:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - docker build --tag $IMAGE_NAME:$DEFAULT_TAG --tag $IMAGE_NAME:${CI_COMMIT_SHORT_SHA} --network host --file ./Dockerfile --rm .

push-image:
  stage: push
  dependencies:
    - build-image
  script:
    - docker push $IMAGE_NAME:${CI_COMMIT_SHORT_SHA}
    - docker push $IMAGE_NAME:$DEFAULT_TAG