image: docker:stable

services:
  - docker:28.1.1-dind-rootless

stages:
  - build
  - push

variables:
  IMAGE_NAME: trackMate
  DEFAULT_TAG: latest
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_REGISTRY: $DOCKER_REGISTRY
  DOCKER_REGISTRY_TOKEN_RW: $AUTH_TOKEN_USER
  DOCKER_REGISTRY_USER_RW: $DOCKER_REGISTRY_USER_RW

# before_script:
#   - echo -n $CI_REGISTRY_USER | docker login --username $DOCKER_REGISTRY_USER_RW --password-stdin $DOCKER_REGISTRY

# after_script:
#   - docker logout $DOCKER_REGISTRY

#production image
build-image:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - docker build --tag $IMAGE_NAME:$DEFAULT_TAG --tag $IMAGE_NAME:${CI_COMMIT_SHORT_SHA} --network host --file ./Dockerfile --rm .

push-image:
  stage: push
  dependencies:
    - build-image
  script:
    - docker push $IMAGE_NAME:${CI_COMMIT_SHORT_SHA}
    - docker push $IMAGE_NAME:$DEFAULT_TAG