image: docker:stable

services:
  - docker:28.1.1-dind-rootless

stages:
  - build
  - push

variables:
  IMAGE_NAME: trackMate
  DEFAULT_TAG: latest
  DOCKER_TLS_CERTDIR: ""
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_REGISTRY_TOKEN_RW: dckr_pat_upFFFXwhUXdb9_y5FSG8KWeebYI
  DOCKER_REGISTRY_USER_RW: vidol

before_script:
  - echo -n $DOCKER_REGISTRY_TOKEN_RW | docker login --username $DOCKER_REGISTRY_USER_RW --password-stdin $DOCKER_REGISTRY

after_script:
  - docker logout $DOCKER_REGISTRY

#production image
build-image:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - docker build --tag $IMAGE_NAME:$DEFAULT_TAG --tag $IMAGE_NAME:${CI_COMMIT_SHORT_SHA} --network host --file ./Dockerfile --rm .

push-image:
  stage: push
  dependencies:
    - build-image
  script:
    - docker push $IMAGE_NAME:${CI_COMMIT_SHORT_SHA}
    - docker push $IMAGE_NAME:$DEFAULT_TAG