image: docker:stable

services:
  - name: docker:28.1.1-dind
    alias: docker

stages:
  - build-and-push

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DEFAULT_TAG: latest
  REGISTRY: registry.gitlab.com/vivividolov-group/track-mate

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY

after_script:
  - docker logout $REGISTRY

# Frontend build + push
frontend:
  stage: build-and-push
  script:
    - docker build -t $REGISTRY/frontend:$DEFAULT_TAG -t $REGISTRY/frontend:${CI_COMMIT_SHORT_SHA} ./frontend
    - docker push $REGISTRY/frontend:$DEFAULT_TAG
    - docker push $REGISTRY/frontend:${CI_COMMIT_SHORT_SHA}

# Backend build + push
backend:
  stage: build-and-push
  script:
    - docker build -t $REGISTRY/backend:$DEFAULT_TAG -t $REGISTRY/backend:${CI_COMMIT_SHORT_SHA} ./backend
    - docker push $REGISTRY/backend:$DEFAULT_TAG
    - docker push $REGISTRY/backend:${CI_COMMIT_SHORT_SHA}