image: docker:stable

services:
  - name: docker:28.1.1-dind
    alias: docker

stages:
  - build
  - push

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DEFAULT_TAG: latest
  REGISTRY: registry.gitlab.com/vivividolov-group/track-mate

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

after_script:
  - docker logout registry.gitlab.com

# Build Frontend
build-frontend:
  stage: build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week
  script:
    - docker build -t $REGISTRY/frontend:$DEFAULT_TAG -t $REGISTRY/frontend:${CI_COMMIT_SHORT_SHA} ./frontend

# Push Frontend
push-frontend:
  stage: push
  dependencies:
    - build-frontend
  script:
    - docker push $REGISTRY/frontend:$DEFAULT_TAG
    - docker push $REGISTRY/frontend:${CI_COMMIT_SHORT_SHA}

# Build Backend
build-backend:
  stage: build
  artifacts:
    paths:
      - backend/dist
    expire_in: 1 week
  script:
    - docker build -t $REGISTRY/backend:$DEFAULT_TAG -t $REGISTRY/backend:${CI_COMMIT_SHORT_SHA} ./backend

# Push Backend
push-backend:
  stage: push
  dependencies:
    - build-backend
  script:
    - docker push $REGISTRY/backend:$DEFAULT_TAG
    - docker push $REGISTRY/backend:${CI_COMMIT_SHORT_SHA}