image: docker:stable

services:
  - name: docker:28.1.1-dind
    alias: docker

stages:
  - build
  - push

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DEFAULT_TAG: latest
  REGISTRY: registry.gitlab.com/vivividolov-group/trackmate

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY

after_script:
  - docker logout $REGISTRY

build-frontend:
  stage: build
  script:
    - docker build -t $REGISTRY/frontend:$DEFAULT_TAG -t $REGISTRY/frontend:${CI_COMMIT_SHORT_SHA} ./frontend
  artifacts:
    name: frontend-image
    paths: []
    expire_in: 1 hour

build-backend:
  stage: build
  script:
    - docker build -t $REGISTRY/backend:$DEFAULT_TAG -t $REGISTRY/backend:${CI_COMMIT_SHORT_SHA} ./backend
  artifacts:
    name: backend-image
    paths: []
    expire_in: 1 hour

push-frontend:
  stage: push
  needs: [build-frontend]
  script:
    - docker push $REGISTRY/frontend:$DEFAULT_TAG
    - docker push $REGISTRY/frontend:${CI_COMMIT_SHORT_SHA}

push-backend:
  stage: push
  needs: [build-backend]
  script:
    - docker push $REGISTRY/backend:$DEFAULT_TAG
    - docker push $REGISTRY/backend:${CI_COMMIT_SHORT_SHA}