services:
  client:
    image: client-dev-i
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client-dev-c
    volumes:
      - ./frontend:/client
      - frontend_node_modules:/client/node_modules/
    ports:
      - 5173:5173
  backend:
    image: backend-dev-i
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev-c
    volumes:
      - ./backend:/backend
      - backend_node_modules:/client/node_modules/
    ports:
      - 3000:3000
      - 3002:3002
    depends_on:
      - db
    env_file:
      - ./backend/.env
  db:
    container_name: db-prod-c
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
volumes: 
  frontend_node_modules:
  backend_node_modules: