services:
  client:
    image: client-dev-i
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./frontend:/client
      - node_modules:/client/node_modules/
    ports:
      - 5173:5173
volumes: 
  node_modules: