FROM node:alpine
WORKDIR /backend
COPY package*.json ./
COPY prisma ./prisma/
RUN apk add --no-cache openssl
RUN npm install
RUN npm install pm2 -g
COPY . .
RUN npm run build

EXPOSE 3000

CMD ["pm2-runtime", "dist/main.js"]